name = "Infrastructure Pack"
uid = "fff6f6c8-248a-11de-8c30-362b9e100010"
version = 10
copyright = "Ejionar/Varaxis/Puledro/Yaru/mythixgirl/Atom7k/CaptainChunck/Jagged/Donnerbalken/Gottenolm85/Uveso/Mirddes & some units and textures from Blackops Unleashed & Total Mayhem"
description = "The Ultimate Upgrade Mod Pack CREDIT TO THE FOLLOWING;-  Ejionar, Varaxis & mythixgirl for T2/T3 storage; Puledro, Yaru & mythixgirl for EXMEX; Atom7k for T4 power; Gottenolm85 & Donnerbalken for Upgradeable HydroCarbon Plants; Captain Chunck for T4 Hives; Uveso for T4 "Village" Shield and T4 Storage; Jagged & Mirddes for compiling other peoples mods and making other miscellaneous contributions"
author = "Ejionar Varaxis Puledro Yaru mythixgirl Atom7k CaptainChunck Jagged Donnerbalken Gottenolm85 Uveso Mirddes"
icon = "/mods/Infrastructure_Pack/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
