name = "T4 Energy Generators"
uid = "ce809895-b8a4-469a-b3cc-a6bfee32dcee"
description = "T4 Energy Generators. These are upgradable from T3 energy generators as well. They are by far not as powerfull as Paragon because I want a stable T4 resource base for my T5 Ultra Weapon Mod I'm developing. Paragon is nerfed for that cause"
author = "Atom7k"
icon = "/mods/T4_Energy_Gen_Pack/modicon.png"
url = ""
version = 1.0
copyright = "Atom7k"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}