name = "Amphibious Antinuke"
uid = "2ab18db8-ea79-11e6-b006-92361f002671"
version = 1
copyright = "whatever"
description = "Makes antinukes amphibious (for use with tvg)"
author = "Quark"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
