name = "Infrastructure Pack"
uid = "fff6f6c8-248a-11de-8c30-362b9e100011"
version = 11
copyright = "Ejionar/Varaxis/mythixgirl/Puledro/Yaru/Atom7k/CaptainChunck/Jagged/Uveso/Mirddes/Quark/DoomHammer/BarryBlack/IceDragon/ExavierMacbeth/Lt_hawkeye/orangeknight/Tpapp/MarLo"
description = "T2&T3 Storage. T4mexes. T2,T3,T4 Hydrocarbons. T4 AntiNuke Shields. T4 Hives. T4 Power. AntiTeleport. Amphibious AntiNukes. Flying Engineers. credit to Ejionar/Varaxis/mythixgirl/Puledro/Yaru/Atom7k/CaptainChunck/Jagged/Uveso/Mirddes/Quark/DoomHammer/BarryBlack/IceDragon/ExavierMacbeth/Lt_hawkeye/orangeknight/Tpapp/MarLo"
author = "ManyWonderfulPeople"
icon = "/mods/Infrastructure Pack/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
