name = "Infrastructure Pack"
uid = "fff6f6c8-248a-11de-8c30-362b9e100016"
version = 16
copyright = "Ejionar/Varaxis/mythixgirl/Puledro/Yaru/Atom7k/CaptainChunck/Jagged/Uveso/Mirddes/Quark/DoomHammer/BarryBlack/IceDragon/ExavierMacbeth/Lt_hawkeye/orangeknight/Tpapp/MarLo"
description = "T2T3Storage T2-T4Hydro T4mexes/Hives/Power T4AntiNukeShields T2T3AntiTeleport AmphibiousAntiNukes FlyingEngineers CREDIT TO  Ejionar/Varaxis/mythixgirl/Puledro/Yaru/Atom7k/CaptainChunck/Jagged/Uveso/Mirddes /Quark/DoomHammer/BarryBlack/IceDragon/ExavierMacbeth/Lt_hawkeye/orangeknight/Tpapp/MarLo"
author = "ManyWonderfulPeople"
icon = "/mods/Infrastructure Pack/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
