name = "Infrastructure Pack"
uid = "fff6f6c8-248a-11de-8c30-362b9e100010"
version = 10
copyright = "Ejionar/Varaxis/mythixgirl/Puledro/Yaru/Atom7k/CaptainChunck/Jagged/Uveso/Mirddes & some units and textures from Blackops Unleashed & Total Mayhem"
description = "T2&T3 Storage. T4mexes. T2,T3,T4 Hydrocarbons. T4 Shields. T4 Hives. T4 Power. credit to Ejionar/Varaxis/mythixgirl/Puledro/Yaru/Atom7k/CaptainChunck/Jagged/Uveso/Mirddes"
author = "Many Wonderful People"
icon = "/mods/Infrastructure Pack/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
