name = "Flying engineers"
uid = "b5bcfd65-57fc-405e-8e9b-a124eab3c27faa"
version = 1
copyright = "BarryBlack"
description = "This mod greatly improves gameplay speed as air units require less pathfinding. It will improve overall performance due to this. This mod allows your T1-3 engineers, now including Seraphin, to fly, like the old TA flying engineers"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
